/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.feesmanagementsysteminjava;

import java.awt.Color;

/**
 *
 * @author muskan jaiswal
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jp_af = new javax.swing.JPanel();
        adlbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jp_sr = new javax.swing.JPanel();
        slbl = new javax.swing.JLabel();
        rlbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jp_ec = new javax.swing.JPanel();
        eclbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jp_vc = new javax.swing.JPanel();
        vclbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jp_vrt = new javax.swing.JPanel();
        vrtlbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jp_vrd = new javax.swing.JPanel();
        vrdlbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jp_l = new javax.swing.JPanel();
        lolbl = new javax.swing.JLabel();
        jp_a = new javax.swing.JPanel();
        albl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\muskan jaiswal\\Documents\\NetBeansProjects\\com.mycompany_FeesManagementSystemInJava_jar_1.0-SNAPSHOT\\src\\main\\java\\image\\home.png")); // NOI18N
        jLabel1.setText(" Home Page");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 270, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 117));

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_af.setBackground(new java.awt.Color(250, 250, 250));
        jp_af.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jp_af.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_afMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_afMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_afMouseExited(evt);
            }
        });
        jp_af.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adlbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adlbl.setText("ADD FEES");
        adlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adlblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adlblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adlblMouseExited(evt);
            }
        });
        jp_af.add(adlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 33, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\muskan jaiswal\\Documents\\NetBeansProjects\\com.mycompany_FeesManagementSystemInJava_jar_1.0-SNAPSHOT\\src\\main\\java\\image\\add.png")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jp_af.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 31, 31));

        jPanel2.add(jp_af, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 140, 90));

        jp_sr.setBackground(new java.awt.Color(250, 250, 250));
        jp_sr.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jp_sr.setPreferredSize(new java.awt.Dimension(140, 90));
        jp_sr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_srMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_srMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_srMouseExited(evt);
            }
        });
        jp_sr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        slbl.setText("SEARCH");
        slbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                slblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                slblMouseExited(evt);
            }
        });
        jp_sr.add(slbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 20, 65, -1));

        rlbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rlbl.setText("REACORD");
        rlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rlblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rlblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rlblMouseExited(evt);
            }
        });
        jp_sr.add(rlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 46, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\muskan jaiswal\\Documents\\NetBeansProjects\\com.mycompany_FeesManagementSystemInJava_jar_1.0-SNAPSHOT\\src\\main\\java\\image\\search circle.png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jp_sr.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 31, 31));

        jPanel2.add(jp_sr, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        jp_ec.setBackground(new java.awt.Color(250, 250, 250));
        jp_ec.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jp_ec.setPreferredSize(new java.awt.Dimension(140, 90));
        jp_ec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_ecMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_ecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_ecMouseExited(evt);
            }
        });
        jp_ec.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eclbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eclbl.setText("EDIT COURSE");
        eclbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eclblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eclblMouseEntered(evt);
            }
        });
        jp_ec.add(eclbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 33, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\muskan jaiswal\\Documents\\NetBeansProjects\\com.mycompany_FeesManagementSystemInJava_jar_1.0-SNAPSHOT\\src\\main\\java\\image\\edit.png")); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });
        jp_ec.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 31, 31));

        jPanel2.add(jp_ec, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, -1, -1));

        jp_vc.setBackground(new java.awt.Color(250, 250, 250));
        jp_vc.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jp_vc.setPreferredSize(new java.awt.Dimension(140, 90));
        jp_vc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_vcMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_vcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_vcMouseExited(evt);
            }
        });
        jp_vc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vclbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vclbl.setText("VIEW COUSE");
        vclbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vclblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vclblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vclblMouseExited(evt);
            }
        });
        jp_vc.add(vclbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 32, 90, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\muskan jaiswal\\Documents\\NetBeansProjects\\com.mycompany_FeesManagementSystemInJava_jar_1.0-SNAPSHOT\\src\\main\\java\\image\\view.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jp_vc.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 31, 31));

        jPanel2.add(jp_vc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        jp_vrt.setBackground(new java.awt.Color(250, 250, 250));
        jp_vrt.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jp_vrt.setPreferredSize(new java.awt.Dimension(140, 90));
        jp_vrt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_vrtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_vrtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_vrtMouseExited(evt);
            }
        });
        jp_vrt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vrtlbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vrtlbl.setText("VIEW REPORT");
        vrtlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vrtlblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vrtlblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vrtlblMouseExited(evt);
            }
        });
        jp_vrt.add(vrtlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 31, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\muskan jaiswal\\Documents\\NetBeansProjects\\com.mycompany_FeesManagementSystemInJava_jar_1.0-SNAPSHOT\\src\\main\\java\\image\\book.png")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jp_vrt.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 31, 31));

        jPanel2.add(jp_vrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        jp_vrd.setBackground(new java.awt.Color(250, 250, 250));
        jp_vrd.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jp_vrd.setPreferredSize(new java.awt.Dimension(140, 90));
        jp_vrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_vrdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_vrdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_vrdMouseExited(evt);
            }
        });
        jp_vrd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vrdlbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vrdlbl.setText("VIEW RECORD");
        vrdlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vrdlblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vrdlblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vrdlblMouseExited(evt);
            }
        });
        jp_vrd.add(vrdlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 33, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\muskan jaiswal\\Documents\\NetBeansProjects\\com.mycompany_FeesManagementSystemInJava_jar_1.0-SNAPSHOT\\src\\main\\java\\image\\viewr.png")); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        jp_vrd.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 31, 31));

        jPanel2.add(jp_vrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, -1, -1));

        jp_l.setBackground(new java.awt.Color(250, 250, 250));
        jp_l.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jp_l.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_lMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_lMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_lMouseExited(evt);
            }
        });

        lolbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lolbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\muskan jaiswal\\Documents\\NetBeansProjects\\com.mycompany_FeesManagementSystemInJava_jar_1.0-SNAPSHOT\\src\\main\\java\\image\\leftaaa 5 black.png")); // NOI18N
        lolbl.setText("LOGOUT");
        lolbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lolblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lolblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lolblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jp_lLayout = new javax.swing.GroupLayout(jp_l);
        jp_l.setLayout(jp_lLayout);
        jp_lLayout.setHorizontalGroup(
            jp_lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_lLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lolbl, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );
        jp_lLayout.setVerticalGroup(
            jp_lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_lLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(lolbl)
                .addContainerGap())
        );

        jPanel2.add(jp_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 110, -1));

        jp_a.setBackground(new java.awt.Color(250, 250, 250));
        jp_a.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jp_a.setPreferredSize(new java.awt.Dimension(116, 43));
        jp_a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_aMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_aMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_aMouseExited(evt);
            }
        });

        albl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        albl.setIcon(new javax.swing.ImageIcon("C:\\Users\\muskan jaiswal\\Documents\\NetBeansProjects\\com.mycompany_FeesManagementSystemInJava_jar_1.0-SNAPSHOT\\src\\main\\java\\image\\admin 5 black.png")); // NOI18N
        albl.setText("ABOUT");
        albl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                alblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jp_aLayout = new javax.swing.GroupLayout(jp_a);
        jp_a.setLayout(jp_aLayout);
        jp_aLayout.setHorizontalGroup(
            jp_aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_aLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(albl, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        jp_aLayout.setVerticalGroup(
            jp_aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_aLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(albl)
                .addContainerGap())
        );

        jPanel2.add(jp_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 470, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1030, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jp_afMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_afMouseClicked
     AddFees af=new AddFees();
     af.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jp_afMouseClicked

    private void jp_afMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_afMouseEntered
Color c1=new Color(245,245,245); 
jp_af.setBackground(c1);
    }//GEN-LAST:event_jp_afMouseEntered

    private void jp_afMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_afMouseExited
Color c1=new Color(250,250,250); 
jp_af.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_jp_afMouseExited

    private void jp_srMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_srMouseEntered
Color c1=new Color(245,245,245); 
jp_sr.setBackground(c1);
    }//GEN-LAST:event_jp_srMouseEntered

    private void jp_srMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_srMouseExited
Color c1=new Color(250,250,250); 
jp_sr.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_jp_srMouseExited

    private void jp_ecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_ecMouseEntered
Color c1=new Color(245,245,245); 
jp_ec.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_jp_ecMouseEntered

    private void jp_ecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_ecMouseExited
Color c1=new Color(250,250,250); 
jp_ec.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jp_ecMouseExited

    private void jp_vcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_vcMouseEntered
Color c1=new Color(245,245,245); 
jp_vc.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_jp_vcMouseEntered

    private void jp_vcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_vcMouseExited
Color c1=new Color(250,250,250); 
jp_vc.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_jp_vcMouseExited

    private void jp_vrtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_vrtMouseEntered
Color c1=new Color(245,245,245); 
jp_vrt.setBackground(c1);     // TODO add your handling code here:
    }//GEN-LAST:event_jp_vrtMouseEntered

    private void jp_vrtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_vrtMouseExited
Color c1=new Color(250,250,250); 
jp_vrt.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_jp_vrtMouseExited

    private void jp_vrdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_vrdMouseEntered
Color c1=new Color(245,245,245); 
jp_vrd.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jp_vrdMouseEntered

    private void jp_vrdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_vrdMouseExited
Color c1=new Color(250,250,250); 
jp_vrd.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jp_vrdMouseExited

    private void jp_lMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_lMouseEntered
Color c1=new Color(211,211,211); 
jp_l.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_jp_lMouseEntered

    private void jp_lMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_lMouseExited
Color c1=new Color(250,250,250); 
jp_l.setBackground(c1);       // TODO add your handling code here:
    }//GEN-LAST:event_jp_lMouseExited

    private void jp_aMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_aMouseEntered
Color c1=new Color(211,211,211); 
jp_a.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jp_aMouseEntered

    private void jp_aMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_aMouseExited
Color c1=new Color(250,250,250); 
jp_a.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_jp_aMouseExited

    private void adlblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adlblMouseExited
    Color c1=new Color(211,211,211); 
jp_l.setForeground(c1);     // TODO add your handling code here:
    }//GEN-LAST:event_adlblMouseExited

    private void adlblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adlblMouseEntered
Color c1=new Color(245,245,245); 
jp_af.setBackground(c1);// TODO add your handling code here:
    }//GEN-LAST:event_adlblMouseEntered

    private void lolblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lolblMouseEntered
Color c1=new Color(211,211,211); 
jp_l.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_lolblMouseEntered

    private void lolblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lolblMouseExited
Color c1=new Color(250,250,250); 
jp_l.setBackground(c1);  // TODO add your handling code here:
    }//GEN-LAST:event_lolblMouseExited

    private void alblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alblMouseEntered
Color c1=new Color(211,211,211); 
jp_a.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_alblMouseEntered

    private void adlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adlblMouseClicked
    AddFees af=new AddFees();
     af.setVisible(true);
     this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_adlblMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
    AddFees af=new AddFees();
     af.setVisible(true);
     this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
Color c1=new Color(245,245,245); 
jp_af.setBackground(c1);       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
Color c1=new Color(211,211,211); 
jp_af.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    private void slblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slblMouseExited
Color c1=new Color(250,250,250); 
jp_sr.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_slblMouseExited

    private void rlblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rlblMouseExited
Color c1=new Color(250,250,250); 
jp_sr.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_rlblMouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
Color c1=new Color(245,245,245); 
jp_sr.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void slblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slblMouseEntered
Color c1=new Color(245,245,245); 
jp_sr.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_slblMouseEntered

    private void rlblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rlblMouseEntered
Color c1=new Color(245,245,245); 
jp_sr.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_rlblMouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
Color c1=new Color(250,250,250); 
jp_sr.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
Color c1=new Color(245,245,245); 
jp_ec.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseEntered

    private void eclblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eclblMouseEntered
Color c1=new Color(245,245,245); 
jp_ec.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_eclblMouseEntered

    private void vclblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vclblMouseEntered
Color c1=new Color(245,245,245); 
jp_vc.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_vclblMouseEntered

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
Color c1=new Color(245,245,245); 
jp_vc.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    private void vclblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vclblMouseExited
Color c1=new Color(250,250,250); 
jp_vc.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_vclblMouseExited

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
Color c1=new Color(250,250,250); 
jp_vc.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseExited

    private void vrtlblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vrtlblMouseExited
Color c1=new Color(250,250,250); 
jp_vrt.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_vrtlblMouseExited

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
Color c1=new Color(250,250,250); 
jp_vrt.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseExited

    private void vrtlblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vrtlblMouseEntered
Color c1=new Color(245,245,245); 
jp_vrt.setBackground(c1);          // TODO add your handling code here:
    }//GEN-LAST:event_vrtlblMouseEntered

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
Color c1=new Color(245,245,245); 
jp_vrt.setBackground(c1);          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void vrdlblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vrdlblMouseEntered
Color c1=new Color(245,245,245); 
jp_vrd.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_vrdlblMouseEntered

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
Color c1=new Color(245,245,245); 
jp_vrd.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseEntered

    private void vrdlblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vrdlblMouseExited
Color c1=new Color(250,250,250); 
jp_vrd.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_vrdlblMouseExited

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
Color c1=new Color(250,250,250); 
jp_vrd.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseExited

    private void jp_srMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_srMouseClicked
SearchRecords search=new SearchRecords();
search.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jp_srMouseClicked

    private void slblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slblMouseClicked
SearchRecords search=new SearchRecords();
search.setVisible(true);
this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_slblMouseClicked

    private void rlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rlblMouseClicked
SearchRecords search=new SearchRecords();
search.setVisible(true);
this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_rlblMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
SearchRecords search=new SearchRecords();
search.setVisible(true);
this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void lolblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lolblMouseClicked
        LogInPage lip=new LogInPage();
        lip.setVisible(true);
        this.dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_lolblMouseClicked

    private void jp_lMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_lMouseClicked
        LogInPage lip=new LogInPage();
        lip.setVisible(true);
        this.dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_jp_lMouseClicked

    private void alblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alblMouseClicked
        CopyrightPage crp=new CopyrightPage();
        crp.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_alblMouseClicked

    private void jp_aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_aMouseClicked
        CopyrightPage crp=new CopyrightPage();
        crp.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jp_aMouseClicked

    private void alblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alblMouseExited
        Color c1=new Color(250,250,250);
        jp_a.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_alblMouseExited

    private void jp_ecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_ecMouseClicked
       EditCourse edit=new EditCourse();
        edit.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jp_ecMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       EditCourse edit=new EditCourse();
        edit.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void eclblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eclblMouseClicked
       EditCourse edit=new EditCourse();
        edit.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_eclblMouseClicked

    private void vrdlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vrdlblMouseClicked
       EditCourse edit=new EditCourse();
        edit.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_vrdlblMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
       EditCourse edit=new EditCourse();
        edit.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jp_vrdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_vrdMouseClicked
       EditCourse edit=new EditCourse();
        edit.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jp_vrdMouseClicked

    private void jp_vrtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_vrtMouseClicked
GenerateReport gr=new GenerateReport();
gr.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jp_vrtMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
GenerateReport gr=new GenerateReport();
gr.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void vrtlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vrtlblMouseClicked
GenerateReport gr=new GenerateReport();
gr.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_vrtlblMouseClicked

    private void vclblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vclblMouseClicked
CourseList cl=new CourseList();
cl.setVisible(true);
this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_vclblMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
CourseList cl=new CourseList();
cl.setVisible(true);
this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jp_vcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_vcMouseClicked
CourseList cl=new CourseList();
cl.setVisible(true);
this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jp_vcMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adlbl;
    private javax.swing.JLabel albl;
    private javax.swing.JLabel eclbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jp_a;
    private javax.swing.JPanel jp_af;
    private javax.swing.JPanel jp_ec;
    private javax.swing.JPanel jp_l;
    private javax.swing.JPanel jp_sr;
    private javax.swing.JPanel jp_vc;
    private javax.swing.JPanel jp_vrd;
    private javax.swing.JPanel jp_vrt;
    private javax.swing.JLabel lolbl;
    private javax.swing.JLabel rlbl;
    private javax.swing.JLabel slbl;
    private javax.swing.JLabel vclbl;
    private javax.swing.JLabel vrdlbl;
    private javax.swing.JLabel vrtlbl;
    // End of variables declaration//GEN-END:variables
}
