/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.feesmanagementsysteminjava;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author muskan jaiswal
 */
public class PrintReciept extends javax.swing.JFrame {

    /**
     * Creates new form PrintReciept
     */
    public PrintReciept() {
        initComponents();
        getRecords();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_edit = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_home = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_sr = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_ec = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_cl = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_var = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_back = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_lo = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btn_print = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panel_print = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_pay_mode = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbl_cc_dd_upi = new javax.swing.JLabel();
        txt_cc_dd_upi = new javax.swing.JLabel();
        lbl_bank = new javax.swing.JLabel();
        txt_bank = new javax.swing.JLabel();
        txt_y2 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_rf = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_y1 = new javax.swing.JLabel();
        txt_receiptNo = new javax.swing.JLabel();
        txt_gst = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_rf = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txt_course = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txt_amount_in_word = new javax.swing.JLabel();
        txt_amount = new javax.swing.JLabel();
        txt_cgst = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_sgst = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();
        txt_remark = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_edit.setBackground(new java.awt.Color(204, 204, 255));
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editMouseExited(evt);
            }
        });
        btn_edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Edit");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        btn_edit.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 35));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\muskan jaiswal\\Documents\\NetBeansProjects\\com.mycompany_FeesManagementSystemInJava_jar_1.0-SNAPSHOT\\src\\main\\java\\image\\write.png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        btn_edit.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, 30));

        jPanel1.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 260, 50));

        btn_home.setBackground(new java.awt.Color(204, 204, 255));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
        });
        btn_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("HOME");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        btn_home.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 35));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\muskan jaiswal\\Documents\\NetBeansProjects\\com.mycompany_FeesManagementSystemInJava_jar_1.0-SNAPSHOT\\src\\main\\java\\image\\home black 5.png")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        btn_home.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, 30));

        jPanel1.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 260, 50));

        btn_sr.setBackground(new java.awt.Color(204, 204, 255));
        btn_sr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_srMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_srMouseExited(evt);
            }
        });
        btn_sr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Search Record");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        btn_sr.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 35));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\muskan jaiswal\\Documents\\NetBeansProjects\\com.mycompany_FeesManagementSystemInJava_jar_1.0-SNAPSHOT\\src\\main\\java\\image\\search 10.png")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        btn_sr.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 50));

        jPanel1.add(btn_sr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 260, 50));

        btn_ec.setBackground(new java.awt.Color(204, 204, 255));
        btn_ec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ecMouseExited(evt);
            }
        });
        btn_ec.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Edit Course");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        btn_ec.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 35));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\muskan jaiswal\\Documents\\NetBeansProjects\\com.mycompany_FeesManagementSystemInJava_jar_1.0-SNAPSHOT\\src\\main\\java\\image\\edit list 5.png")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        btn_ec.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, 30));

        jPanel1.add(btn_ec, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 260, 50));

        btn_cl.setBackground(new java.awt.Color(204, 204, 255));
        btn_cl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_clMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_clMouseExited(evt);
            }
        });
        btn_cl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Couse List");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        btn_cl.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 35));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\muskan jaiswal\\Documents\\NetBeansProjects\\com.mycompany_FeesManagementSystemInJava_jar_1.0-SNAPSHOT\\src\\main\\java\\image\\view 5.png")); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        btn_cl.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, 30));

        jPanel1.add(btn_cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 260, 50));

        btn_var.setBackground(new java.awt.Color(204, 204, 255));
        btn_var.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_varMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_varMouseExited(evt);
            }
        });
        btn_var.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("View All Records");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        btn_var.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 35));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\muskan jaiswal\\Documents\\NetBeansProjects\\com.mycompany_FeesManagementSystemInJava_jar_1.0-SNAPSHOT\\src\\main\\java\\image\\book.png")); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        btn_var.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, 30));

        jPanel1.add(btn_var, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 260, 50));

        btn_back.setBackground(new java.awt.Color(204, 204, 255));
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_backMouseExited(evt);
            }
        });
        btn_back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Back");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        btn_back.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 35));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\muskan jaiswal\\Documents\\NetBeansProjects\\com.mycompany_FeesManagementSystemInJava_jar_1.0-SNAPSHOT\\src\\main\\java\\image\\leftaaa 5 black.png")); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        btn_back.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, 30));

        jPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 260, 50));

        btn_lo.setBackground(new java.awt.Color(204, 204, 255));
        btn_lo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_loMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_loMouseExited(evt);
            }
        });
        btn_lo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("Logout");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });
        btn_lo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 35));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\muskan jaiswal\\Documents\\NetBeansProjects\\com.mycompany_FeesManagementSystemInJava_jar_1.0-SNAPSHOT\\src\\main\\java\\image\\out left 5.png")); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel17MouseExited(evt);
            }
        });
        btn_lo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, 30));

        jPanel1.add(btn_lo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 260, 50));

        btn_print.setBackground(new java.awt.Color(204, 204, 255));
        btn_print.setForeground(new java.awt.Color(0, 0, 102));
        btn_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_printMouseExited(evt);
            }
        });
        btn_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("Print");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
        });
        btn_print.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 35));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 102));
        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\muskan jaiswal\\Documents\\NetBeansProjects\\com.mycompany_FeesManagementSystemInJava_jar_1.0-SNAPSHOT\\src\\main\\java\\image\\print simple.png")); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19MouseExited(evt);
            }
        });
        btn_print.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, 30));

        jPanel1.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 260, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 780));

        panel_print.setBackground(new java.awt.Color(255, 255, 255));
        panel_print.setPreferredSize(new java.awt.Dimension(1345, 745));
        panel_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_print.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1070, 10));

        txt_pay_mode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_pay_mode.setText("Payment Mode :");
        panel_print.add(txt_pay_mode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        txt_date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_date.setText("Receipt Number :");
        panel_print.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 170, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Receipt Number :");
        panel_print.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("The Following Payment in the college office form the year");
        panel_print.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Payment Mode :");
        panel_print.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        lbl_cc_dd_upi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_cc_dd_upi.setText("Cheque Number :");
        panel_print.add(lbl_cc_dd_upi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        txt_cc_dd_upi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_cc_dd_upi.setText("Cheque Number :");
        panel_print.add(txt_cc_dd_upi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        lbl_bank.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_bank.setText("Bank Name :");
        panel_print.add(lbl_bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        txt_bank.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_bank.setText("Cheque Number :");
        panel_print.add(txt_bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        txt_y2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_y2.setText("2023");
        panel_print.add(txt_y2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("Amount");
        panel_print.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 380, -1, -1));

        txt_rf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_rf.setText("Received From :");
        panel_print.add(txt_rf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setText("to");
        panel_print.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

        txt_y1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_y1.setText("2023");
        panel_print.add(txt_y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        txt_receiptNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_receiptNo.setText("Receipt Number :");
        panel_print.add(txt_receiptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        txt_gst.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_gst.setText("Date :");
        panel_print.add(txt_gst, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 200, -1, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setText("Date :");
        panel_print.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, -1, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setText("GSTIN:");
        panel_print.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 0, 102));
        panel_print.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 540, 390, 10));

        jSeparator2.setForeground(new java.awt.Color(51, 0, 102));
        panel_print.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 1070, 10));

        lbl_rf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_rf.setText("Received From :");
        panel_print.add(lbl_rf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setText("Sr No");
        panel_print.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel39.setText("SGST(9%)");
        panel_print.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, -1, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel40.setText("Head");
        panel_print.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));

        txt_course.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_course.setText("Head");
        panel_print.add(txt_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 90, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel42.setText("CGST(9%)");
        panel_print.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 70, -1));

        txt_amount_in_word.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_amount_in_word.setText("Total in words :");
        panel_print.add(txt_amount_in_word, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 600, 20));

        txt_amount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_amount.setText("Head");
        panel_print.add(txt_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, 100, -1));

        txt_cgst.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_cgst.setText("Head");
        panel_print.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 470, 120, -1));

        jSeparator3.setForeground(new java.awt.Color(51, 0, 102));
        panel_print.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 1070, 20));

        txt_sgst.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_sgst.setText("Head");
        panel_print.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 510, 130, 20));

        txt_total.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_total.setText("Total");
        panel_print.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 550, 200, 20));

        txt_remark.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_remark.setText("Total in words :");
        panel_print.add(txt_remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, 520, 20));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(51, 0, 102));
        jLabel49.setText("Print Receipt");
        panel_print.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel50.setText("Total in words :");
        panel_print.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 100, 20));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel51.setText("Remark :");
        panel_print.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 60, 20));

        jSeparator4.setForeground(new java.awt.Color(51, 0, 102));
        panel_print.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 650, 280, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Receiver Signature");
        panel_print.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 660, -1, 20));

        getContentPane().add(panel_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 1070, 700));

        setSize(new java.awt.Dimension(1389, 784));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseEntered
Color c1=new Color(211,211,211); 
btn_edit.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editMouseEntered

    private void btn_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseExited
Color c1=new Color(204,204,255); 
btn_edit.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editMouseExited

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
    Color c1=new Color(211,211,211); 
btn_home.setBackground(c1);    // TODO add your handling code here:
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
     Color c1=new Color(204,204,255); 
btn_home.setBackground(c1);    // TODO add your handling code here:
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_srMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_srMouseEntered
    Color c1=new Color(211,211,211); 
btn_sr.setBackground(c1);    // TODO add your handling code here:
    }//GEN-LAST:event_btn_srMouseEntered

    private void btn_srMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_srMouseExited
     Color c1=new Color(204,204,255); 
btn_sr.setBackground(c1);    // TODO add your handling code here:
    }//GEN-LAST:event_btn_srMouseExited

    private void btn_ecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ecMouseEntered
     Color c1=new Color(211,211,211); 
btn_ec.setBackground(c1);   // TODO add your handling code here:
    }//GEN-LAST:event_btn_ecMouseEntered

    private void btn_ecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ecMouseExited
      Color c1=new Color(204,204,255); 
btn_ec.setBackground(c1);   // TODO add your handling code here:
    }//GEN-LAST:event_btn_ecMouseExited

    private void btn_clMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clMouseEntered
     Color c1=new Color(211,211,211); 
btn_cl.setBackground(c1);   // TODO add your handling code here:
    }//GEN-LAST:event_btn_clMouseEntered

    private void btn_clMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clMouseExited
     Color c1=new Color(204,204,255); 
btn_cl.setBackground(c1);    // TODO add your handling code here:
    }//GEN-LAST:event_btn_clMouseExited

    private void btn_varMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_varMouseEntered
    Color c1=new Color(211,211,211); 
btn_var.setBackground(c1);    // TODO add your handling code here:
    }//GEN-LAST:event_btn_varMouseEntered

    private void btn_varMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_varMouseExited
      Color c1=new Color(204,204,255); 
btn_var.setBackground(c1);    // TODO add your handling code here:
    }//GEN-LAST:event_btn_varMouseExited

    private void btn_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseEntered
    Color c1=new Color(211,211,211); 
btn_back.setBackground(c1);    // TODO add your handling code here:
    }//GEN-LAST:event_btn_backMouseEntered

    private void btn_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseExited
     Color c1=new Color(204,204,255); 
btn_back.setBackground(c1);     // TODO add your handling code here:
    }//GEN-LAST:event_btn_backMouseExited

    private void btn_loMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loMouseEntered
    Color c1=new Color(211,211,211); 
btn_lo.setBackground(c1);    // TODO add your handling code here:
    }//GEN-LAST:event_btn_loMouseEntered

    private void btn_loMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loMouseExited
     Color c1=new Color(204,204,255); 
btn_lo.setBackground(c1);     // TODO add your handling code here:
    }//GEN-LAST:event_btn_loMouseExited

    private void btn_printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseEntered
Color c1=new Color(211,211,211); 
btn_print.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_printMouseEntered

    private void btn_printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseExited
     Color c1=new Color(204,204,255); 
btn_print.setBackground(c1);     // TODO add your handling code here:
    }//GEN-LAST:event_btn_printMouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
Color c1=new Color(211,211,211); 
btn_edit.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
Color c1=new Color(211,211,211); 
btn_edit.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
Color c1=new Color(204,204,255); 
btn_edit.setBackground(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
      Color c1=new Color(211,211,211); 
btn_print.setBackground(c1);   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseEntered

    private void jLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseExited
 Color c1=new Color(204,204,255); 
btn_edit.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseExited

    private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseExited
 Color c1=new Color(204,204,255); 
btn_print.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseExited

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
 Color c1=new Color(204,204,255); 
btn_lo.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseExited
 Color c1=new Color(204,204,255); 
btn_lo.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseExited

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
     Color c1=new Color(211,211,211); 
btn_back.setBackground(c1);    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
 Color c1=new Color(204,204,255); 
btn_back.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
 Color c1=new Color(204,204,255); 
btn_back.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
 Color c1=new Color(204,204,255); 
btn_var.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
 Color c1=new Color(204,204,255); 
btn_var.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
 Color c1=new Color(204,204,255); 
btn_cl.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
 Color c1=new Color(204,204,255); 
btn_cl.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
 Color c1=new Color(204,204,255); 
btn_ec.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
 Color c1=new Color(204,204,255); 
btn_ec.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
 Color c1=new Color(204,204,255); 
btn_sr.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
 Color c1=new Color(204,204,255); 
btn_sr.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
 Color c1=new Color(204,204,255); 
btn_edit.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
 Color c1=new Color(204,204,255); 
btn_home.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
Color c1=new Color(211,211,211); 
btn_home.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
Color c1=new Color(211,211,211); 
btn_home.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
Color c1=new Color(211,211,211); 
btn_sr.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
Color c1=new Color(211,211,211); 
btn_sr.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
Color c1=new Color(211,211,211); 
btn_ec.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
Color c1=new Color(211,211,211); 
btn_ec.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
Color c1=new Color(211,211,211); 
btn_cl.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
Color c1=new Color(211,211,211); 
btn_cl.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
Color c1=new Color(211,211,211); 
btn_var.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
Color c1=new Color(211,211,211); 
btn_var.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
Color c1=new Color(211,211,211); 
btn_back.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
Color c1=new Color(211,211,211); 
btn_lo.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseEntered

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
Color c1=new Color(211,211,211); 
btn_lo.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered
Color c1=new Color(211,211,211); 
btn_print.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
Color c1=new Color(204,204,255); 
btn_edit.setBackground(c1);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseExited

    private void btn_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseClicked
   PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                panel_print.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }     // TODO add your handling code here:
    }//GEN-LAST:event_btn_printMouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                panel_print.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                panel_print.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
UpdateFeesDetails update=new UpdateFeesDetails();
update.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    public void getRecords(){
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
        String url="jdbc:mysql://localhost:3306/feesmanagementsystem?zeroDateTimeBehavior=CONVERT_TO_NULL";
        Connection con=DriverManager.getConnection(url,"root","2309");
        PreparedStatement st=con.prepareStatement("select * from fees_details order by reciept_no desc limit 1");
        ResultSet rs=st.executeQuery();
        rs.next();
        txt_receiptNo.setText(rs.getString("reciept_no"));
        txt_pay_mode.setText(rs.getString("payment_mode"));
        String paymentMode=rs.getString("payment_mode");
        if(paymentMode.equalsIgnoreCase("cash")){
            lbl_cc_dd_upi.setText("");
            txt_cc_dd_upi.setText("");
            lbl_bank.setText("");
            txt_bank.setText("");
        }
        if(paymentMode.equalsIgnoreCase("cheque")){
            lbl_cc_dd_upi.setText("Cheque Number");
            txt_cc_dd_upi.setText(rs.getString("cheque_no"));
            lbl_bank.setText("Bank Name");
            txt_bank.setText(rs.getString("bank_name"));
        }
        if(paymentMode.equalsIgnoreCase("dd")){
            lbl_cc_dd_upi.setText("DD Number");
            txt_cc_dd_upi.setText(rs.getString("dd_no"));
            lbl_bank.setText("Bank Name");
            txt_bank.setText(rs.getString("bank_name"));
        }
        if(paymentMode.equalsIgnoreCase("upi")){
            lbl_cc_dd_upi.setText("UPI ID");
            txt_cc_dd_upi.setText(rs.getString("upi_id"));
            lbl_bank.setText("");
            txt_bank.setText("");
        }
        txt_rf.setText(rs.getString("student_name"));
        txt_date.setText(rs.getString("date"));
        txt_gst.setText(rs.getString("gstin"));
        txt_y1.setText(rs.getString("year1"));
        txt_y2.setText(rs.getString("year2"));
        txt_amount.setText(rs.getString("amount"));
        txt_cgst.setText(rs.getString("cgst"));
        txt_sgst.setText(rs.getString("sgst"));
        txt_total.setText(rs.getString("total_amount"));
        txt_amount_in_word.setText(rs.getString("total_in_words"));
        txt_course.setText(rs.getString("course_name"));
        txt_remark.setText(rs.getString("remark"));
        }
        catch(Exception e){
        
    }
    }
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReciept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_back;
    private javax.swing.JPanel btn_cl;
    private javax.swing.JPanel btn_ec;
    private javax.swing.JPanel btn_edit;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_lo;
    private javax.swing.JPanel btn_print;
    private javax.swing.JPanel btn_sr;
    private javax.swing.JPanel btn_var;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_bank;
    private javax.swing.JLabel lbl_cc_dd_upi;
    private javax.swing.JLabel lbl_rf;
    private javax.swing.JPanel panel_print;
    private javax.swing.JLabel txt_amount;
    private javax.swing.JLabel txt_amount_in_word;
    private javax.swing.JLabel txt_bank;
    private javax.swing.JLabel txt_cc_dd_upi;
    private javax.swing.JLabel txt_cgst;
    private javax.swing.JLabel txt_course;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_gst;
    private javax.swing.JLabel txt_pay_mode;
    private javax.swing.JLabel txt_receiptNo;
    private javax.swing.JLabel txt_remark;
    private javax.swing.JLabel txt_rf;
    private javax.swing.JLabel txt_sgst;
    private javax.swing.JLabel txt_total;
    private javax.swing.JLabel txt_y1;
    private javax.swing.JLabel txt_y2;
    // End of variables declaration//GEN-END:variables
}
